export const formFields = [
     'PFirstName' ,
       ' PLastName' ,
        'GFirstName' ,
        'GLastName' ,
        'Phone' ,
        'ACCNo' ,
        'SSN' ,
       'ReferredBy' ,
        'MedPayID' ,
        'ClaimNO' ,
       'eid' ,
        'Status' ,
        'MPNumber' ,
        'Adjuster' ,
        'ServiceDate' ,
        'BirthDate' ,
        'ActiveStatus' ,
        'HomePhone' ,
        'CellPhone' ,
        'WorkHomePhone' ,
        'PatientId' ,
        'AdmitDate' ]