export const SEARCH_EMPLOYEE_INPUT = 'SEARCH_EMPLOYEE_INPUT';
export const SEARCH_EMPLOYEE_SUCCESS = 'SEARCH_EMPLOYEE_SUCCESS';

export const SHOW_EMPLOYER_MENU = 'SHOW_EMPLOYER_MENU';

export const HIDE_EMPLOYER_MENU = 'HIDE_EMPLOYER_MENU';
export const SAVE_EMPLOYEE_SUCCESS='SAVE_EMPLOYEE_SUCCESS';
export const SAVE_EMPLOYEE='SAVE_EMPLOYEE';
export const SELECT_EMPLOYEE='SELECT_EMPLOYEE';
export const EDIT_EMPLOYEE='EDIT_EMPLOYEE';
export const CLEARDATA='CLEARDATA';