export const GET_INDEX_PAGE_INFO = 'GET_INDEX_PAGE_INFO';

export const GET_INDEX_PAGE_INFO_SUCCESS = 'GET_INDEX_PAGE_INFO_SUCCESS';

export const GET_INDEX_PAGE_INFO_ERROR = 'GET_INDEX_PAGE_INFO_ERROR';

export const GET_LATEST_ANNOUNCEMENTS = 'GET_LATEST_ANNOUNCEMENTS';

export const GET_LATEST_ANNOUNCEMENTS_SUCCESS = 'GET_LATEST_ANNOUNCEMENTS_SUCCESS';

export const GET_LATEST_ANNOUNCEMENTS_ERROR = 'GET_LATEST_ANNOUNCEMENTS_ERROR';