// Search 
export const SHOW_SEARCH_MENU = 'SHOW_SEARCH_MENU';

export const HIDE_SEARCH_MENU = 'HIDE_SEARCH_MENU';

export const SEARCH_RESULT='SEARCH_RESULT';
export const SEARCH_RESULT_SUCCESS='SEARCH_RESULT_SUCCESS';
export const SHOW_SEARCH_DATA='SHOW_SEARCH_DATA';
export const CLEAR_DATA='CLEAR_DATA';